---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(scales)
library(caret)
library(klaR)
library(rpart)
library(party)
library(randomForest)
library(RColorBrewer)
library(tidyverse)
```

```{r}
# Custom Functions

# Round to the nearest "m" (for example 5)
mround = function(x,base){ 
        rounded = base * round(x / base) 
        return(rounded)
}

```


```{r}
raw_df = read.csv('winemag-data_first150k.csv')
head(raw_df)
```


```{r}
us_wine_df = raw_df %>% 
  filter(country == 'US') %>%
  select(designation,points,price,province,region_1,variety,winery) %>%
  na.omit()

qualityCutoff = 90
us_wine_df = us_wine_df %>%
  mutate(Quality = ifelse(points>=as.name(qualityCutoff),
                          paste0(as.name(qualityCutoff),'+'),
                          paste0('<',as.name(qualityCutoff)))) %>%
  select(-points,-price)
us_wine_df$Quality = as.factor(us_wine_df$Quality)
```






```{r}
head(us_wine_df)
```


```{r}
ggplot(us_wine_df,aes(x=Quality)) + geom_bar(aes(y = (..count..)/sum(..count..)))
```


```{r}
set.seed(101)
trainIndex = createDataPartition(us_wine_df$Quality, p=0.70, list=FALSE)
us_wine_train = us_wine_df[ trainIndex,]
us_wine_test = us_wine_df[-trainIndex,]
```

```{r}
#Decision Tree
fit = rpart(Quality ~. , data = us_wine_train)
printcp(fit)
```

```{r}
plot(fit, uniform=TRUE, 
  	main="Regression Tree for Wine Reviews")
text(fit, use.n=TRUE, all=TRUE, cex=.8,pretty=1)
```


```{r}
par(mfrow=c(1,2))
rsq.rpart(fit)
```



```{r}
# Naive Bayes
fit <- NaiveBayes(Quality~., data=us_wine_train)
summary(fit)
```

```{r}
# NB Predictions
x_test = us_wine_test[,1:5]
y_test = us_wine_test[,6]
predictions = predict(fit, x_test)
```

```{r}
# NB Confusion Matrix
confusionMatrix(predictions$class, y_test)
```

```{r}

```

```{r}

```

